# Generated by Django 5.0.6 on 2024-07-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_marca_rename_descricao_cor_nome"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="acessorio",
            options={"verbose_name": "Acessorio", "verbose_name_plural": "Acessorios"},
        ),
        migrations.AlterField(
            model_name="marca",
            name="nacionalidade",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
